### ISSUE TITLE
[Ports]: Backport client side changes

### ISSUE THREAD

**Issue by playwrightmachine** [microsoft/playwright-dotnet#1754]
Please backport client side changes:

Relevant
  - [x] https://github.com/microsoft/playwright/commit/7c89bc162a60b104553c5ac4429ded9f599bacc4 (fix: leaking route handlers when times is used in Page.route (#9234))
  - [x] https://github.com/microsoft/playwright/commit/3cc839e01327dbf5b6e2a889da8da373b7efd503 (fix(route): catch all Route methods when page closes (#10140))
  - [x] https://github.com/microsoft/playwright/commit/b79daec8e04f63d32faf6130caf3207d8aec771e (chore: make it possible to override Locator.dragTo(strict) (#11457))
  - [x] https://github.com/microsoft/playwright/commit/f29a673b4c37f1c132ef180938dc20cee0211d3d (fix: do not mute route handler exceptions (#11555))
  - [x] https://github.com/microsoft/playwright/commit/4d42f6a1c4bb182dae5bf614357fc8c47d1c4527 (chore: remove unused _waitingForObject from Connection (#11474))
  - [ ] https://github.com/microsoft/playwright/commit/ab9d5a0dc4744fbfad6be2ed219b81977b6aa97d (chore(tracing): add tracing to APIRequestContext (#11502))
  - [ ] https://github.com/microsoft/playwright/commit/64e7557fb9052a14b02161a9e341e7b350d5c004 (fix: falsey behavior in route.continue, page.post, testInfo.attach (#11421))
  - [ ] https://github.com/microsoft/playwright/commit/800b813d4b95a6243f73d7950d5d455b23afe3c4 (chore(test runner): prepare to per-fixture timeout (#11605))
  - [ ] https://github.com/microsoft/playwright/commit/687a16b848b9fa7c2a9b92e6b4a9dc96388ba0b1 (feat(locator): introduce locator.page() getter (#11630))
