### ISSUE TITLE
[Ports]: Backport client side changes

### ISSUE THREAD

**Issue by playwrightmachine** [microsoft/playwright-dotnet#2011]
Please backport client side changes:
  - [x] https://github.com/microsoft/playwright/commit/5a0445b8dac2febe9702904d816327769e10886e (feat(remote): let client enable/disable sock proxy (#12086))
  - [x] https://github.com/microsoft/playwright/commit/363b8a697095ccd0ea0dd3a1c1ade136aa555b70 (feat: support `mask` option in screenshot methods (#12072))
  - [x] https://github.com/microsoft/playwright/commit/396d9201458a48ee37cf1e4e51acb51a23df53b1 (feat(test-runner): implement expect(pageOrLocator).toHaveScreenshot (#12242))
  - [x] https://github.com/microsoft/playwright/commit/61a6cdde704b659ba2a8e450db48127c00f64a5b (feat(api): expose locator.highlight (#12420))
  - [x] https://github.com/microsoft/playwright/commit/fd1a1a2b1cf415c002e8850beca7f7e5ecc00092 (feat(android): Adding custom port parameter to connect to different adb server port (#12220))
  - [x] https://github.com/microsoft/playwright/commit/5fd43edcbb1ff453e68cf809d69692d1fbfc68d0 (chore: fix android tests after #12220 (#12535))
  - [x] https://github.com/microsoft/playwright/commit/d836ed41d352c37ae263713ff3d0ff8a7937d8e3 (feat(remote): send 'x-playwright-browser' header (#12556))
