### ISSUE TITLE
[Ports]: Backport client side changes

### ISSUE THREAD

**Issue by playwrightmachine** [microsoft/playwright-dotnet#2294]
Please backport client side changes:
  - [x] https://github.com/microsoft/playwright/commit/306ab34aa3bcdfbb2369e1c698a161565bacc275 (feat(assertions): support toBeEnabled({ enabled }) (#17058))
  - [x] https://github.com/microsoft/playwright/commit/f0c581060959bf680d2165f38e29743388d03b21 (feat(assertions): support toBeEditable({ editable }) (#17065))
  - [x] https://github.com/microsoft/playwright/commit/c91df61ca33c133046425d40b45dfc25ec331673 (chore: optionally connect instead of launching (#17174))
  - [x] https://github.com/microsoft/playwright/commit/bca13bc35aead0122b0609ea18a0769864616c29 (feat(assertions): support toBeVisible({ visible }) (#17207))
  - [x] https://github.com/microsoft/playwright/commit/17b203affbc373fd5c7d8e643285e1262350cc67 (feat: added follow and redirect arguments to fetch (#17033))
