### ISSUE TITLE
[Ports]: Backport client side changes

### ISSUE THREAD

**Issue by playwrightmachine** [microsoft/playwright-dotnet#2395]
Please backport client side changes:
  - [x] https://github.com/microsoft/playwright/commit/4e58b0c2eafa5976abd03e91aa52d7164a9a0855 (chore: render timed out error message when expect timeouts (#18863))
  - [x] https://github.com/microsoft/playwright/commit/5ac426b3d5d45bd1f7092445d04b99e39b76d700 (chore: expose utility script to inner evaluates (#19147))
  - [x] https://github.com/microsoft/playwright/commit/f0e8d8f0744b4ba431a599abaa3999aff760cd85 (feat(api): introduce route.fetch and route.fulfill(json) (#19184))
  - [x] https://github.com/microsoft/playwright/commit/7aa3935dcce55a892f9f2b5982f2db048c1c889f (chore: match selected options by both value and label (#19316))
  - [x] https://github.com/microsoft/playwright/commit/256e9fd443c0e67dc6a42d3f1e0c40680dc7a5f1 (feat(connect): allow exposing local network to the remote browser (experimental) (#19372))
  - [x] https://github.com/microsoft/playwright/commit/6cadc56ea3783eac501f60dbfb4cfd42062c1f98 (feat(api): allow getByTestId(regex) (#19419))
  - [x] https://github.com/microsoft/playwright/commit/d1559a0fcc6ecd12bf6bacd3f66d848ea78aaa3a (chore: route.fetch(postData) (#19436))
  - [x] https://github.com/microsoft/playwright/commit/17a00744593adb6948b788b971f339901ac05c9e (feat(api): introduce Locator.all, enumerate (#19461))
  - [x] https://github.com/microsoft/playwright/commit/0e2732decfb511a6d625f66deae2fac760c6d87e (feat(api): introduce expect().toPass (#19463))
  - [x] https://github.com/microsoft/playwright/commit/3afd83c8cce5b036ad93b0dca188e8a5bd59abbf (chore: withdraw locator.enumerate (#19484))
  - [x] https://github.com/microsoft/playwright/commit/3f333a8ef72c2a81ed63e15764863be51f22b333 (chore: simplify post_data processing (#19490))
  - [x] https://github.com/microsoft/playwright/commit/412c11db208da0543137ac781e775578a72eaece (fix(reuse): make sure all dispose and close sequences are executed (#19572))
  - [x] https://github.com/microsoft/playwright/commit/d7e7cab44a28cf46e99fd9a0902a054e9088183e (fix: properly handle negated timed-out `toPass` matcher (#19580))
  - [x] https://github.com/microsoft/playwright/commit/95cc5c2a2e74bfa3437dea26395c661238876974 (fix(electron): fix the directory app path (#19601))
  - [x] https://github.com/microsoft/playwright/commit/fe989d95eb709ff436d4cace44d66acc6950abde (chore(electron): move loader to be preload (#19650))
  - [x] https://github.com/microsoft/playwright/commit/3883799d68e165567d7ea6a8636ce7c88cddbc99 (feat: introduce `locator.viewportRatio` (#19761))
  - [x] https://github.com/microsoft/playwright/commit/1afa38d5a7a8255eb4bd6e9deeea04911cf26304 (chore(expect): extract polling from expect.poll and expect().toPass (#19882))
  - [x] https://github.com/microsoft/playwright/commit/10ccfa95173f80574ce4dfd8570204e88169e30e (feat(fetch): happy eyeballs (#19902))
  - [x] https://github.com/microsoft/playwright/commit/31a63b5c2a750d8fb3d7d2184ea098f0604b1cc7 (fix(reuse): make reuse work with tracing (#19733))
  - [x] https://github.com/microsoft/playwright/commit/2a49c5e4986c2d5bc570e9199b0688c70ac48336 (feat(expect): introduce expect(locator).toIntersectViewport() (#19901))
  - [x] https://github.com/microsoft/playwright/commit/3f0adf5dd063cb0b0464d5e786379085750ec16d (chore: release from pause when the page closes (#19975))
  - [x] https://github.com/microsoft/playwright/commit/0fe327c21ba9b7369f64b148bd47279baab49566 (chore: return Promise<any> in {page,context}.route (#20005))
  - [x] https://github.com/microsoft/playwright/commit/d1c161ce99d79f7eb3b3ea279e47f7e13da4eb79 (chore: merge the util exports (#20110))
