### ISSUE TITLE
[Ports]: Backport client side changes

### ISSUE THREAD

**Issue by playwrightmachine** [microsoft/playwright-dotnet#2463]
Please backport client side changes:
  - [x] https://github.com/microsoft/playwright/commit/cab52cded9a23e15af8c0b3647754bd093f05e94 (chore: consolidate route handling logic in NetworkRouter (#20353))
  - [x] https://github.com/microsoft/playwright/commit/7d7e66f450d020d8a031cfc7af9a4aa9a5175b36 (chore: group test runner files by process (#20425))
  - [x] https://github.com/microsoft/playwright/commit/ead4989947462682063552cc2664c8b1022ca662 (fix(api): Response.finished() throws when target closes (#20453))
  - [x] https://github.com/microsoft/playwright/commit/d458e84f5b1f61556cbfb3e28d50f63684eca92a (feat(route): match pattern on the server side (#20410))
  - [x] https://github.com/microsoft/playwright/pull/20510/files
  - [x] https://github.com/microsoft/playwright/commit/6ad4687f4d1d666b6c4ceadf7c88b339f2614cd6 (feat(route): add maxRedirects option to Route.fetch (#20567))
  - [x] https://github.com/microsoft/playwright/commit/4f6110503238c6a8fccd2e4f69639f6250ea7230 (fix: swallow expect.soft errors inside successful toPass matcher (#20509))
  - [x] https://github.com/microsoft/playwright/commit/f45f20a8c95923b01c72d09089d994c12d1f0f10 (fix: handle not.toPass() with expect.soft inside (#20596))
  - [x] https://github.com/microsoft/playwright/commit/edfff8cd8c1d27e719dc18389459684d8370871f (test: run more tests in 'service' mode (#20734))
  - [x] https://github.com/microsoft/playwright/commit/6e5964cccdb0ccc4c453895dedf63b95acef2797 (fix(connect): respect launch options when turning into connect (#20757))
  - [x] https://github.com/microsoft/playwright/commit/ab4cd83e449b4c25f4e224f5ba2d85feb04c0448 (chore: move testInfo and timeoutManager to worker/ (#20803))
  - [x] https://github.com/microsoft/playwright/commit/68e170ef898e7f973dded1dde68114115ed82d98 (feat: implement expect(locator).toBeInViewport() (#20668))
  - [x] https://github.com/microsoft/playwright/commit/1db04f2839c73debc7be827403c7b67f26af0063 (fix: simplify protocol for toBeInViewport (#20960))
